---
# tasks file for roles/httdp
- name: Run HTTPD
  docker_container:
    name: rproxy-front
    image: korglos/tp-devops-httpd:latest
    
    pull: yes
    ports:
      - "80:80"
      - "8080:8080"
    networks:
      - name: tp1-network2