---
# tasks file for roles/api
- name: Run API
  docker_container:
    name: api-back
    image: korglos/tp-devops-simple-api:latest
    pull: yes
    env_file: /files/.env
    networks:
      - name: tp1-network1
      - name: tp1-network2