name: Deploy Application

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      ANSIBLE_HOST_KEY_CHECKING: "False"  # Désactive la vérification de l'empreinte SSH

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Ansible
      run: |
        python -m pip install --upgrade pip
        pip install ansible

    - name: Configure SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H mathis.clavioz.takima.cloud >> ~/.ssh/known_hosts

    - name: Create .env file from GitHub Secret
      run: |
        echo "${{ secrets.ANSIBLE_ENV }}" > TP3/ansible/files/.env

    - name: Run Ansible Playbook
      run: |
        ansible-playbook -i TP3/ansible/inventories/setup.yml TP3/ansible/playbook.yml
