name: CI Develop devops 2025

on:
  # L'action se déclenche lors d'un push sur la branche main ou develop
  push:
    branches:
      - develop
  # L'action se déclenche lors d'une pull request
  pull_request:
      - develop

jobs:
  test-backend:
    # On spécifie l'OS sur lequel on veut lancer l'action
    runs-on: ubuntu-22.04
    steps:
      # Checkout your GitHub code using actions/checkout@v4
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up JDK 21 using actions/setup-java@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        # On spécifie la version de Java et la distribution
        with:
          java-version: '21'
          distribution: 'corretto'

      # Build and test the app with Maven
      - name: Build and test with Maven
        # On se place dans le dossier où se trouve le pom.xml et on lance mvn clean verify
        run: |
          cd Docker/TP1/API/simple-api-student-main
          mvn clean verify

  sonar-backend:
    # On spécifie l'OS sur lequel on veut lancer l'action
    runs-on: ubuntu-22.04
    steps:
      # Checkout your GitHub code using actions/checkout@v4
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up JDK 21 using actions/setup-java@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        # On spécifie la version de Java et la distribution
        with:
          java-version: '21'
          distribution: 'corretto'

      # Build and test the app with Maven
      - name: Build and test with Maven
        # On se place dans le dossier où se trouve le pom.xml et on lance mvn clean verify
        run: |
          cd Docker/TP1/API/simple-api-student-main
          mvn -B verify sonar:sonar -Dsonar.projectKey=Korglos_DevOpsS8 -Dsonar.organization=korglos -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}