name: CI devops 2025

on:
  # L'action se déclenche lors d'un push sur la branche main ou develop
  push:
    branches:
      - main
      - develop
  # L'action se déclenche lors d'une pull request
  pull_request:

jobs:
  test-backend:
    # On spécifie l'OS sur lequel on veut lancer l'action
    runs-on: ubuntu-22.04
    steps:
      # Checkout your GitHub code using actions/checkout@v4
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up JDK 21 using actions/setup-java@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        # On spécifie la version de Java et la distribution
        with:
          java-version: '21'
          distribution: 'corretto'

      # Build and test the app with Maven
      - name: Build and test with Maven
        # On se place dans le dossier où se trouve le pom.xml et on lance mvn clean verify
        run: |
          cd Docker/TP1/API/simple-api-student-main
          mvn -B verify sonar:sonar -Dsonar.projectKey=Korglos_DevOpsS8 -Dsonar.organization=korglos -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}  --file Docker/TP1/API/simple-api-student-main/pom.xml


  # Define job to build and publish Docker images
  build-and-push-docker-image:
    needs: test-backend
    # Run only when code is compiling and tests are passing
    runs-on: ubuntu-22.04

    # Steps to perform in job
    steps:
      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build image and push backend
        uses: docker/build-push-action@v6
        with:
          # Relative path to the place where source code with Dockerfile is located
          context: ./Docker/TP1/API/simple-api-student-main
          # Note: tags have to be all lowercase
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build image and push database
        uses: docker/build-push-action@v6
        with:
          # Relative path to the place where source code with Dockerfile is located
          context: ./Docker/TP1/DataBase
          # Note: tags have to be all lowercase
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-database:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build image and push httpd
        uses: docker/build-push-action@v6
        with:
          # Relative path to the place where source code with Dockerfile is located
          context: ./Docker/TP1/Front
          # Note: tags have to be all lowercase
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-httpd:latest
          push: ${{ github.ref == 'refs/heads/main' }}